name: Build kernel - Debug

on:
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/build-debug-kernel.yml"
      - ".github/workflows/build-kernel-a13-5.15.yml"
      - ".github/workflows/build-kernel-a13-5.10.yml"
      - ".github/workflows/build-kernel-a12-5.10.yml"
      - ".github/workflows/build-kernel-wsa.yml"
      - ".github/workflows/build-kernel-arcvm.yml"
      - ".github/workflows/gki-kernel.yml"
      - ".github/scripts/build_a13.sh"
      - ".github/scripts/build_a12.sh"
      - "kernel/**"
  workflow_dispatch:

jobs:
  build-debug-kernel-a12-510:
    strategy:
      matrix:
        include:
          - sub_level: 43
            os_patch_level: 2021-10
          - sub_level: 66
            os_patch_level: 2022-01
          - sub_level: 81
            os_patch_level: 2022-03
          - sub_level: 101
            os_patch_level: 2022-05
          - sub_level: 110
            os_patch_level: 2022-07
          - sub_level: 117
            os_patch_level: 2022-09
          - sub_level: 136
            os_patch_level: 2022-11
          - sub_level: 149
            os_patch_level: 2023-01
          - sub_level: 160
            os_patch_level: 2023-03
          - sub_level: 168
            os_patch_level: 2023-05
          - sub_level: 177
            os_patch_level: 2023-07
          - sub_level: 187
            os_patch_level: lts
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android12-5.10
      version_name: android12-5.10.${{ matrix.sub_level }}
      tag: android12-5.10-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: "5.10"
      debug: true

  build-debug-kernel-a12-510-mainline:
    strategy:
      matrix:
        include:
          - sub_level: 185
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android12-5.10
      version_name: android12-5.10.${{ matrix.sub_level }}
      tag: android12-5.10
      os_patch_level: mainline
      patch_path: "5.10"
      debug: true

  build-debug-kernel-a13-510-mainline:
    strategy:
      matrix:
        include:
          - sub_level: 186
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android13-5.10
      version_name: android13-5.10.${{ matrix.sub_level }}
      tag: android13-5.10
      os_patch_level: mainline
      patch_path: "5.10"
      debug: true

  build-debug-kernel-a13-515-mainline:
    strategy:
      matrix:
        include:
          - sub_level: 119
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android13-5.15
      version_name: android13-5.15.${{ matrix.sub_level }}
      tag: android13-5.15
      os_patch_level: mainline
      patch_path: "5.15"
      debug: true

  build-debug-kernel-a13-510:
    strategy:
      matrix:
        include:
          - sub_level: 107
            os_patch_level: 2022-11
          - sub_level: 149
            os_patch_level: 2023-01
          - sub_level: 157
            os_patch_level: 2023-03
          - sub_level: 168
            os_patch_level: 2023-05
          - sub_level: 177
            os_patch_level: 2023-07
          - sub_level: 186
            os_patch_level: 2023-08
          - sub_level: 187
            os_patch_level: lts
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android13-5.10
      version_name: android13-5.10.${{ matrix.sub_level }}
      tag: android13-5.10-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: "5.10"
      debug: true

  build-debug-kernel-a13-515:
    strategy:
      matrix:
        include:
          - sub_level: 41
            os_patch_level: 2022-11
          - sub_level: 74
            os_patch_level: 2023-01
          - sub_level: 78
            os_patch_level: 2023-03
          - sub_level: 94
            os_patch_level: 2023-05
          - sub_level: 104
            os_patch_level: 2023-07
          - sub_level: 119
            os_patch_level: 2023-08
          - sub_level: 120
            os_patch_level: lts
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android13-5.15
      version_name: android13-5.15.${{ matrix.sub_level }}
      tag: android13-5.15-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: "5.15"
      debug: true

  build-debug-kernel-wsa:
    uses: ./.github/workflows/build-kernel-wsa.yml
    with:
      debug: true

  build-debug-kernel-arcvm:
    uses: ./.github/workflows/build-kernel-arcvm.yml
    with:
      debug: true
