name: Build kernel - Debug

on:
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/build-debug-kernel.yml"
      - ".github/workflows/build-kernel-a13.yml"
      - ".github/workflows/build-kernel-a12.yml"
      - ".github/workflows/build-kernel-wsa.yml"
      - ".github/workflows/build-kernel-arcvm.yml"
      - ".github/workflows/gki-kernel.yml"
      - ".github/scripts/build_a13.sh"
      - ".github/scripts/build_a12.sh"
      - "kernel/**"
  workflow_dispatch:

jobs:
  build-debug-kernel-a12:
    strategy:
      matrix:
        include:
          - sub_level: 66
            os_patch_level: 2022-01
          - sub_level: 81
            os_patch_level: 2022-03
          - sub_level: 101
            os_patch_level: 2022-05
          - sub_level: 110
            os_patch_level: 2022-07
          - sub_level: 117
            os_patch_level: 2022-09
          - sub_level: 136
            os_patch_level: 2022-11
          - sub_level: 149
            os_patch_level: 2023-01
          - sub_level: 160
            os_patch_level: 2023-03
          - sub_level: 168
            os_patch_level: 2023-05
          - sub_level: 177
            os_patch_level: 2023-06
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android12-5.10
      version_name: android12-5.10.${{ matrix.sub_level }}
      tag: android12-5.10-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: "5.10"
      debug: true

  build-debug-kernel-a13:
    strategy:
      matrix:
        include:
          - version: "5.10"
            sub_level: 107
            os_patch_level: 2022-11
          - version: "5.10"
            sub_level: 149
            os_patch_level: 2023-01
          - version: "5.10"
            sub_level: 157
            os_patch_level: 2023-03
          - version: "5.10"
            sub_level: 168
            os_patch_level: 2023-05
          - version: "5.10"
            sub_level: 177
            os_patch_level: 2023-06
          - version: "5.15"
            sub_level: 41
            os_patch_level: 2022-11
          - version: "5.15"
            sub_level: 74
            os_patch_level: 2023-01
          - version: "5.15"
            sub_level: 78
            os_patch_level: 2023-03
          - version: "5.15"
            sub_level: 94
            os_patch_level: 2023-05
          - version: "5.15"
            sub_level: 104
            os_patch_level: 2023-06
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android13-${{ matrix.version }}
      version_name: android13-${{ matrix.version }}.${{ matrix.sub_level }}
      tag: android13-${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: ${{ matrix.version }}
      debug: true

  build-debug-kernel-wsa:
    uses: ./.github/workflows/build-kernel-wsa.yml
    with:
      debug: true

  build-debug-kernel-arcvm:
    uses: ./.github/workflows/build-kernel-arcvm.yml
    with:
      debug: true
