name: Build Kernel - Android 13 5.15

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/build-kernel-a13-5.15.yml"
      - ".github/workflows/gki-kernel.yml"
      - ".github/scripts/build_a13.sh"
      - "kernel/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - ".github/workflows/build-kernel-a13-5.15.yml"
      - ".github/workflows/gki-kernel.yml"
      - ".github/scripts/build-a13.sh"
      - "kernel/**"
  workflow_call:

jobs:
  build-kernel:
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        include:
          # Temporarily disabled for compiling via GitHub Actions
          # - sub_level: 41
          #   os_patch_level: 2022-11
          # - sub_level: 74
          #   os_patch_level: 2023-01
          # - sub_level: 78
          #   os_patch_level: 2023-03
          # - sub_level: 94
          #   os_patch_level: 2023-05
          # - sub_level: 104
          #   os_patch_level: 2023-07
          # - sub_level: 119
          #   os_patch_level: 2023-08
          - sub_level: 120
            os_patch_level: lts
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      version: android13-5.15
      version_name: android13-5.15.${{ matrix.sub_level }}
      tag: android13-5.15-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      patch_path: "5.15"
  upload-artifacts:
    needs: build-kernel
    runs-on: ubuntu-latest
    if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/master' ) || github.ref_type == 'tag' || github.ref == 'refs/heads/ci' }}
    env:
      CHAT_ID: ${{ secrets.CHAT_ID }}
      CACHE_CHAT_ID: ${{ secrets.CACHE_CHAT_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      COMMIT_URL: ${{ github.event.head_commit.url }}
      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - uses: actions/checkout@v3
        with:
          path: KernelSU
          fetch-depth: 0

      - name: List artifacts
        run: |
          tree

      - name: Download prebuilt toolchain
        run: |
          AOSP_MIRROR=https://android.googlesource.com
          BRANCH=master-kernel-build-2022
          git clone $AOSP_MIRROR/platform/prebuilts/build-tools -b $BRANCH --depth 1 build-tools
          git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
          git clone $AOSP_MIRROR/platform/system/tools/mkbootimg -b $BRANCH --depth 1

      - name: Set boot sign key
        env:
          BOOT_SIGN_KEY: ${{ secrets.BOOT_SIGN_KEY }}
        run: |
          if [ ! -z "$BOOT_SIGN_KEY" ]; then
            echo "$BOOT_SIGN_KEY" > ./kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem
          fi

      - name: Build boot images
        run: |
          export AVBTOOL=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/bin/avbtool
          export GZIP=$GITHUB_WORKSPACE/build-tools/path/linux-x86/gzip
          export LZ4=$GITHUB_WORKSPACE/build-tools/path/linux-x86/lz4
          export MKBOOTIMG=$GITHUB_WORKSPACE/mkbootimg/mkbootimg.py
          export UNPACK_BOOTIMG=$GITHUB_WORKSPACE/mkbootimg/unpack_bootimg.py
          cd $GITHUB_WORKSPACE/KernelSU
          export VERSION=$(($(git rev-list --count HEAD) + 10200))
          echo "VERSION: $VERSION"
          cd -
          bash $GITHUB_WORKSPACE/KernelSU/.github/scripts/build_a13.sh
      
      - name: Display structure of boot files
        run: ls -R

      - name: Upload images artifact
        uses: actions/upload-artifact@v3
        with:
          name: boot-images-android13
          path: Image-android13*/*.img.gz

  check-build-kernel:
    strategy:
      matrix:
        include:
          - sub_level: 119
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android13-5.15
      version_name: android13-5.15.${{ matrix.sub_level }}
      tag: android13-5.15
      patch_path: "5.15"
