name: Rustfmt Check

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/rustfmt.yml'
      - 'userspace/ksud/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/rustfmt.yml'
      - 'userspace/ksud/**'

permissions:
  checks: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: LoliGothick/rustfmt-check@master
        with:
          token: ${{ github.token }}
          working-directory: userspace/ksud
